# Generated by Django 2.0.2 on 2018-03-21 03:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=128)),
                ('line', models.CharField(max_length=32)),
                ('col', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=512)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
    ]
